name: Build and push to Dockerhub

on:
  push:
    branches: [ main, master, stable, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.TC_SHOWCASE_DOCKERHUB_USER }}
        password: ${{ secrets.TC_SHOWCASE_DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          4096mm/cloudsovereignty-supplierdomain:latest
          4096mm/cloudsovereignty-supplierdomain:${{ env.SHORT_SHA }}